apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
    name: use-pvspec-shosh
spec:
    volumes:
    - name: pv-1
persistentVolumeClaim:
    claimName: pv-1
containers:
    -image: nginx
    name: use-pv
    volumeMounts:
    - mountPath: /data
      name: pv-1
    resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: Always
status: {}

#kubectl apply -f pv-1.yaml
#pod/use-pvspec-shosh created

