apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    app: nginx-resolver
spec:
  containers:
  - image: nginx
    name: nginx-resolver
    ports:
      -containerPort: 80


#kubectl apply -f nginx-resolver.yaml
