apiVersion: v1
kind: Pod
metadata:
  name: nginx-critical
  labels:
  app: nginx-critical
spec:
  nodeSelector:
    kubernetes.io/hostname: node01
  containers:
  - image: nginx
    name: nginx-critical
    resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: OnFailure
status: {}


#kubectl apply -f nginx-critical.yaml
