apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  labels:
    tier: msg
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    tier: msg

#kubectl apply -f messaging-service.yaml
