apiVersion: v1
kind: Deployment
metadata:
  name: hr-web-app
  labels:
    app: hr-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-web-app-
  template:
    metadata:
      labels:
        app: hr-web-app
    spec:
      containers:
        - name: kodekloud-webapp
          image: kodekloud/webapp-color


#kubectl apply -f hr-web-app.yaml
