apiVersion: v1
kind: Deployment
metadata:
  name: hr-web-app
  labels:
    app: hr-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-web-app-
  template:
    metadata:
      labels:
        app: hr-web-app
    spec:
      containers:
        - name: kodekloud-webapp
          image: kodekloud/webapp-color


#kubectl apply -f hr-web-app.yaml
#deployment.apps/hr-web-app created
#kubectl get po
#NAME                          READY   STATUS    RESTARTS   AGE
#hr-web-app-85dc75bbc6-4ss75   1/1     Running   0          24m
#messaging                     1/1     Running   0          43m
