apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "1000"]


#kubectl apply -f static-busybox.yaml
#pod/static-busybox created
